/********************************************************************
* modules/PairDstFormat/DictionaryFemtoPair.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error modules/PairDstFormat/DictionaryFemtoPair.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDictionaryFemtoPair();
extern void G__cpp_setup_inheritanceDictionaryFemtoPair();
extern void G__cpp_setup_typetableDictionaryFemtoPair();
extern void G__cpp_setup_memvarDictionaryFemtoPair();
extern void G__cpp_setup_globalDictionaryFemtoPair();
extern void G__cpp_setup_memfuncDictionaryFemtoPair();
extern void G__cpp_setup_funcDictionaryFemtoPair();
extern void G__set_cpp_environmentDictionaryFemtoPair();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "FemtoPair.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DictionaryFemtoPairLN_TClass;
extern G__linked_taginfo G__DictionaryFemtoPairLN_TBuffer;
extern G__linked_taginfo G__DictionaryFemtoPairLN_TMemberInspector;
extern G__linked_taginfo G__DictionaryFemtoPairLN_TObject;
extern G__linked_taginfo G__DictionaryFemtoPairLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DictionaryFemtoPairLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictionaryFemtoPairLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DictionaryFemtoPairLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictionaryFemtoPairLN_FemtoDstBranch;
extern G__linked_taginfo G__DictionaryFemtoPairLN_FemtoPair;

/* STUB derived class for protected member access */
